Python for Data Science

Python libraries for data science: 

i) Tensor Flow: It's a library for high performance numerical computations. It's basically a framework where we can define and run computations which involves tensors. Tensors are partially defined computational objects where they will eventually produce a value. 
Features of tensorFlow: i) Majorly used in deep learning models and neural networks.   ii) Reduces the error largely by 50-60% in neural machine translation 
iii) Parallel computing(aka Pipelining) to execute complex models
iv) Seamless library management  

ii) Numpy(Numerical Python): A fundamental package for numerical computation in Python.
It's a generall purpose array-processing package. Contains a N-dimensional array object. 

In [3]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a)
print(a.shape) # gives the shape of array in matrix form

<class 'numpy.ndarray'>
[1 2 3]
(3,)


In [4]:
b= np.arange(12) # np.arange(12).reshape(4,3) Can also arrange here 
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
b.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
import time
import sys

nor = range(1000)
print(sys.getsizeof(5)*len(nor))

28000


In [ ]:
num = np.arange(1000)
print(num.size*num.itemsize) # numpy less memory

8000
8000


In [143]:
size = 100000

L1 = range(size)
L2 = range(size)
A1 = np.arange(1000)
A2 = np.arange(1000)

start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print("Python list took", (time.time()-start)*1000, "ms")

Python list took 9.144783020019531 ms


In [149]:
start = time.time()
result = A1 + A2 # More convinient
print("Numpy array took", (time.time()-start)*1000, "ms") # Faster

Numpy array took 0.1220703125 ms
