Python for Data Science

Python libraries for data science: 

i) Tensor Flow: It's a library for high performance numerical computations. It's basically a framework where we can define and run computations which involves tensors. Tensors are partially defined computational objects where they will eventually produce a value. 
Features of tensorFlow: i) Majorly used in deep learning models and neural networks.   ii) Reduces the error largely by 50-60% in neural machine translation 
iii) Parallel computing(aka Pipelining) to execute complex models
iv) Seamless library management  

ii) Numpy(Numerical Python): A fundamental package for numerical computation in Python.
It's a generall purpose array-processing package. Contains a N-dimensional array object. 

In [7]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a)
print(a.shape) # gives the shape of array in matrix form

<class 'numpy.ndarray'>
[1 2 3]
(3,)


In [ ]:
b= np.arange(12) # np.arange(12).reshape(4,3) Can also arrange here 
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
b.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])